feat(01-building-blocks): change from failed to successful step

diff --git a/.github/workflows/01-building-blocks.yaml b/.github/workflows/01-building-blocks.yaml
--- a/.github/workflows/01-building-blocks.yaml
+++ b/.github/workflows/01-building-blocks.yaml
@@ -1,3 +1,23 @@
+# name: 01 - Building Blocks
+
+# on: push
+
+# jobs:
+#   echo-hello:
+#     runs-on: ubuntu-latest
+#     steps:
+#       - name: Say hello
+#         run: echo "Hello, world!"
+#   echo-goodbye:
+#     runs-on: ubuntu-latest
+#     steps:
+#       - name: Failed step
+#         run: |
+#           echo "I will fail this job"
+#           exit 1
+#       - name: Says goodbye
+#         run: echo "Goodbye, world!"
+
 name: 01 - Building Blocks
 
 on: push
@@ -11,9 +31,9 @@ jobs:
   echo-goodbye:
     runs-on: ubuntu-latest
     steps:
-      - name: Failed step
+      - name: Successful step
         run: |
-          echo "I will fail this job"
-          exit 1
+          echo "I will succeed this job"
+          exit 0
       - name: Says goodbye
         run: echo "Goodbye, world!"
